[package]
name = "into_other"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
engine_traits = { path = "../engine_traits", default-features = false }
kvproto = { git = "https://github.com/TonsnakeLin/kvproto.git" }
raft = { version = "0.7.0", default-features = false, features = ["protobuf-codec"] }
